# resolver: lts-12.21
resolver: lts-14.7
packages:
- .
- /home/user/src/llvm-hs/llvm-hs
- /home/user/src/llvm-hs/llvm-hs-pure
extra-deps:
 - set-extra-1.4.1
 - boolector-0.0.0.11
 - llvm-hs-pretty-0.9.0.0
# Extra directories used by stack for building
extra-include-dirs: [/usr/include/boolector]
